name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to sala telecope'
        type: boolean
        default: false
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install libuhd
        run: sudo apt-get update && sudo apt-get install -y libuhd-dev
      - name: Cache target folder
        uses: actions/cache@v4
        with:
          path: target/release
          key: ${{ runner.os }}-rust-build
      - name: Build
        run: cargo build --verbose --release
      - uses: actions/upload-artifact@v6
        with:
          name: salsa
          path: |
            target/release/backend
            sql_migrations/**
            assets/**
      - name: Run tests
        run: cargo test --verbose --release
      - name: Check format
        run: cargo fmt --check --verbose

  deploy:
    needs: build
    runs-on: salsa
    if: github.ref == 'refs/heads/main' || inputs.deploy

    concurrency:
      group: deploy-main
      cancel-in-progress: false

    steps:
      - name: Stop salsa
        run: |
          sudo systemctl stop salsa.service
      - uses: actions/download-artifact@v7
        with:
          name: salsa
          path: /home/salsa/bin
      - name: Change permissions
        run: |
          chgrp -R salsaowners /home/salsa/bin/target /home/salsa/bin/sql_migrations /home/salsa/bin/assets
          chmod -R g+r /home/salsa/bin/target /home/salsa/bin/sql_migrations /home/salsa/bin/assets
          chmod g+rx /home/salsa/bin/target/release/backend
      - name: Start salsa
        run: |
          systemctl is-enabld -q salsa && sudo systemctl start salsa.service
