name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install libuhd
        run: sudo apt-get update && sudo apt-get install -y libuhd-dev
      - name: Build
        run: cargo build --verbose --release
      - uses: actions/upload-artifact@v6
        with:
          name: salsa
          path: |
            target/release/backend
            sql_migrations/**
            assets/**
      - name: Run tests
        run: cargo test --verbose --release
      - name: Check format
        run: cargo fmt --check --verbose

  deploy:
    needs: build
    runs-on: salsa
    if: github.ref == 'refs/heads/main'

    concurrency:
      group: deploy-main
      cancel-in-progress: false

    steps:
      - uses: actions/download-artifact@v7
        with:
          name: salsa
          path: /home/salsa/bin
      - name: Change permissions
        run: |
          chgrp -R salsaowners /home/salsa/bin/*
          chmod -R g+r /home/salsa/bin/*
          chmod g+rx /home/salsa/bin/target/release/backend
      - name: Display structure of downloaded files
        run: ls -R /home/salsa/bin
